import React from "react";
import { Inter } from "next/font/google";

import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Đăng ký",
  description: "Generated by create next app",
};

const LoginLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <div className="flex items-center justify-center w-[100vw] h-[100vh]">
        {children}
      </div>
    </body>
  </html>
);

export default LoginLayout;
