import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });
const ImageUrl =
  "https://i.pinimg.com/originals/22/c7/70/22c7701fa0602858b0da8f75b37fa6f0.jpg";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex items-center justify-between mx-52">
            <img
              className="block rounded-xl mt-10"
              src={ImageUrl}
              alt="Logo"
            />
            <div className="">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
