import React from "react";
import { Inter } from "next/font/google";

import StyledComponentsRegistry from "../lib/AntdRegistry";

import "./globals.css";
import { StoreProvider } from "@/store/StoreProvider";
import { ApolloWrapper } from "@/lib/ApolloProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "UTE Connect",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <ApolloWrapper>
        <StoreProvider>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </StoreProvider>
      </ApolloWrapper>
    </body>
  </html>
);

export default RootLayout;
