import React from "react";
import { Inter } from "next/font/google";

import StyledComponentsRegistry from "@/lib/AntdRegistry";

import "@/app/globals.css";
import { Layout } from "antd";
import MainHeader from "@/components/mainLayout/MainHeader";
import { Content } from "antd/es/layout/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "UTE Connect",
  description: "Generated by create next app",
};

const HomeLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <StyledComponentsRegistry>
        <Layout>
          <MainHeader />
          <Content className="bg-gray-100 pt-6" style={{minHeight: "95vh", width: "99w"}}>{children}</Content>
        </Layout>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default HomeLayout;
