import type { Metadata } from "next";
import HomeSearch from "@/components/global/home/HomeSearch";
import UserMenu from "@/components/global/user/UserMenu";
import { ScrollArea } from "@/components/ui/scroll-area";

export const metadata: Metadata = {
  title: "My Job",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="bg-gray-100">
      <div className="mx-20 my-0 grid grid-cols-7 pt-8">
        <div className="col-span-1">
          <UserMenu />
        </div>
        <div className="col-span-4 flex justify-center">
          <ScrollArea className="h-[91vh] w-11/12">{children}</ScrollArea>
        </div>
        <div className=" col-span-2">
          <HomeSearch />
        </div>
      </div>
    </div>
  );
}
